name: Android NDK CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - uses: nttld/setup-ndk@v1
      with:
        ndk-version: r27c
        
    - name: Build Sudo-NDK
      run: |
        chmod 777 ./build.sh
        ./build.sh
    
    - uses: actions/upload-artifact@main
      with:
       name: sudo-ndk
       path: |
        magisk_module/*
        !magisk_module/*.DS_Store